### ISSUE TITLE
Activate please

### ISSUE THREAD

**Issue by kangwon-naver** [cpf21d/HelpDesk#1070]
org : cpf21d
repo : cpf21d-90-kangwon-naver
url : https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-90-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-90-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org : cpf21d
repo : cpf21d-91-kangwon-naver
url : https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-91-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-91-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwon-naver** [comment]
org : cpf21d
repo : cpf21d-92-kangwon-naver
url : https://github.com/cpf21d/cpf21d-92-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-92-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-92-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-92-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-92-kangwon-naver

**Comment by kangwon-naver** [comment]
org : cpf21d
repo : cpf21d-90-kangwon-naver
url : https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Please check whether the repo exists
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwonlee** [comment]
org : cpf21d
repo : cpf21d-90-kangwon-naver
url : https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-90-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-90-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwonlee** [comment]
org : cpf21d
repo : cpf21d-91-kangwon-naver
url : https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-91-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-91-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwonlee** [comment]
org : cpf21d
repo : cpf21d-92-kangwon-naver
url : https://github.com/cpf21d/cpf21d-92-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-92-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-92-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-92-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-92-kangwon-naver

**Comment by kangwon-naver** [comment]
org : cpf21d
repo : cpf21d-90-kangwon-naver
url : https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-90-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-90-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org : cpf21d
repo : cpf21d-91-kangwon-naver
url : https://github.com/cpf21d/cpf21d-90-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-91-kangwon-naver
Processing request above
https://github.com/cpf21d/cpf21d-91-kangwon-naver

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-91-kangwon-naver
Success! Start your engine!
https://github.com/cpf21d/cpf21d-91-kangwon-naver
