### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by Seoyunjoo-cpf21d** [cpf21d/HelpDesk#120]
org: cpf21d

repo: cpf21d-04-Seoyunjoo-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-04-Seoyunjoo-cpf21d
Processing request above

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-04-Seoyunjoo-cpf21d
Success! Start your engine!
