### ISSUE TITLE
활성화 부탁드립니다. 02

### ISSUE THREAD

**Issue by ByunghoonJeon-cpf21d** [cpf21d/HelpDesk#122]
org: cpf21d

repo: cpf21d-02-ByunghoonJeon-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-02-ByunghoonJeon-cpf21d
Processing request above
https://github.com/cpf21d/cpf21d-02-ByunghoonJeon-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-02-ByunghoonJeon-cpf21d
Success! Start your engine!
