### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by sanghoon991001** [cpf21d/HelpDesk#145]
org: cpf21d

repo: cpf21d-02-sanghon

url: https://github.com/cpf21d/cpf21d-02-sanghon

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-02-sanghon
Processing request above
https://github.com/cpf21d/cpf21d-02-sanghon

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-02-sanghon
Success! Start your engine!
https://github.com/cpf21d/cpf21d-02-sanghon
