### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by KimMyunCheol-cpf21d** [cpf21d/HelpDesk#2]
org: cpf21d

repo: cpf21d-01-MyunCheol-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-abc_def_123
Processing request above

**Comment by kangwonlee** [comment]
org: cpf21d

repo: cpf21d-01-MyunCheol-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-MyunCheol-cpf21d
Processing request above

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-MyunCheol-cpf21d
Success! Start your engine!

**Comment by kangwonlee** [comment]
@KimMyunCheol-cpf21d Success! Start your engine!
