### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by Minwoo-cpf21d** [cpf21d/HelpDesk#21]
org: cpf21d

repo: cpf21d-01-Minwoo-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-Minwoo-cpf21d
Processing request above

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-Minwoo-cpf21d
Success! Start your engine!
