### ISSUE TITLE
활성화 바랍니다

### ISSUE THREAD

**Issue by ByunghoonJeon-cpf21d** [cpf21d/HelpDesk#3]
org: cpf21d

repo: cpf21d-01-ByunghoonJeon-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-ByunghoonJeon-cpf21d
Processing request above

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-01-ByunghoonJeon-cpf21d
Success! Start your engine!
