### ISSUE TITLE
활성화 해줘요.

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#307]
org: cpf21d

repo: cpf21d-05-jikbakjo

url: https://github.com/cpf21d/cpf21d-05-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-05-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-05-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-05-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-05-jikbakjo
