### ISSUE TITLE
활성화 해줘잉.

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#310]
org: cpf21d

repo: cpf21d-07-jikbakjo

url: https://github.com/cpf21d/cpf21d-07-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-07-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-07-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-07-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-07-jikbakjo
