### ISSUE TITLE
활성화 해죠~!~!

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#311]
org: cpf21d

repo: cpf21d-08-jikbakjo

url: https://github.com/cpf21d/cpf21d-08-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-08-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-08-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-08-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-08-jikbakjo
