### ISSUE TITLE
활성화 바라빈닫.

### ISSUE THREAD

**Issue by MinjunKimKPU** [cpf21d/HelpDesk#339]
org: cpf21d

repo: cpf21d-11-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-11-MinjunKimKPU
Processing request above
https://github.com/cpf21d/cpf21d-11-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-11-MinjunKimKPU
Success! Start your engine!
https://github.com/cpf21d/cpf21d-11-MinjunKimKPU
