### ISSUE TITLE
4활성화바랍니다

### ISSUE THREAD

**Issue by suhan-cpf21d** [cpf21d/HelpDesk#38]
org: cpf21d

repo: cpf21d-04-suhan-cpf21d

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-04-suhan-cpf21d
Processing request above

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-04-suhan-cpf21d
Success! Start your engine!
