### ISSUE TITLE
활성화 해쥬세용

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#424]
org: cpf21d

repo: cpf21d-11-jikbakjo

url: https://github.com/cpf21d/cpf21d-11-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-11-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-11-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-11-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-11-jikbakjo
