### ISSUE TITLE
activate please.

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#517]
org: cpf21d

repo: cpf21d-14-jikbakjo

url: https://github.com/cpf21d/cpf21d-14-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-14-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-14-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-14-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-14-jikbakjo
