### ISSUE TITLE
활성화바라빈다

### ISSUE THREAD

**Issue by MinjunKimKPU** [cpf21d/HelpDesk#520]
org: cpf21d

repo: cpf21d-15-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-15-MinjunKimKPU
Processing request above
https://github.com/cpf21d/cpf21d-15-MinjunKimKPU

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-15-MinjunKimKPU
Success! Start your engine!
https://github.com/cpf21d/cpf21d-15-MinjunKimKPU
