### ISSUE TITLE
활성화!!

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#596]
org: cpf21d

repo: cpf21d-15-jikbakjo

url: https://github.com/cpf21d/cpf21d-15-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-15-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-15-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-15-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-15-jikbakjo
