### ISSUE TITLE
활성화 해주세요우

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#619]
org: cpf21d

repo: cpf21d-16-jikbakjo

url: https://github.com/cpf21d/cpf21d-16-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-16-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-16-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-16-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-16-jikbakjo
