### ISSUE TITLE
활 성 화

### ISSUE THREAD

**Issue by jikbakjo** [cpf21d/HelpDesk#641]
org: cpf21d

repo: cpf21d-18-jikbakjo

url:https://github.com/cpf21d/cpf21d-18-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-18-jikbakjo
Processing request above
https://github.com/cpf21d/cpf21d-18-jikbakjo

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-18-jikbakjo
Success! Start your engine!
https://github.com/cpf21d/cpf21d-18-jikbakjo
