### ISSUE TITLE
활성화

### ISSUE THREAD

**Issue by jeonghyeonS** [cpf21d/HelpDesk#888]
org : cpf21d

repo : cpf21d-25-jeonghyeonS.git

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-25-jeonghyeonS
Processing request above
https://github.com/cpf21d/cpf21d-25-jeonghyeonS

**Comment by kangwon-naver** [comment]
org: cpf21d
repo: cpf21d-25-jeonghyeonS
Success! Start your engine!
https://github.com/cpf21d/cpf21d-25-jeonghyeonS
